# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: simulation.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'simulation.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10simulation.proto\x12\nsimulation\"P\n\x0fSimulateRequest\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x0b\n\x03lab\x18\x02 \x01(\t\x12\x10\n\x08\x64uration\x18\x03 \x01(\x02\x12\x10\n\x08\x64istance\x18\x04 \x01(\x02\"\xd5\x01\n\x10SimulateResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x11\n\tlab_label\x18\x02 \x01(\t\x12\x31\n\x0einput_settings\x18\x03 \x01(\x0b\x32\x19.simulation.InputSettings\x12\"\n\x04logs\x18\x04 \x03(\x0b\x32\x14.simulation.LogEntry\x12\x15\n\rserver_stderr\x18\x05 \x01(\t\x12\r\n\x05\x65rror\x18\x06 \x01(\t\x12\x0f\n\x07\x64\x65tails\x18\x07 \x01(\t\x12\x10\n\x08\x64uration\x18\x08 \x01(\x02\"@\n\rInputSettings\x12\x0b\n\x03lab\x18\x01 \x01(\t\x12\x10\n\x08\x64uration\x18\x02 \x01(\x02\x12\x10\n\x08\x64istance\x18\x03 \x01(\x02\"4\n\x08LogEntry\x12\x0c\n\x04time\x18\x01 \x01(\x02\x12\x0b\n\x03pin\x18\x02 \x01(\x05\x12\r\n\x05level\x18\x03 \x01(\x05\x32\\\n\x11SimulationService\x12G\n\x08Simulate\x12\x1b.simulation.SimulateRequest\x1a\x1c.simulation.SimulateResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'simulation_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SIMULATEREQUEST']._serialized_start=32
  _globals['_SIMULATEREQUEST']._serialized_end=112
  _globals['_SIMULATERESPONSE']._serialized_start=115
  _globals['_SIMULATERESPONSE']._serialized_end=328
  _globals['_INPUTSETTINGS']._serialized_start=330
  _globals['_INPUTSETTINGS']._serialized_end=394
  _globals['_LOGENTRY']._serialized_start=396
  _globals['_LOGENTRY']._serialized_end=448
  _globals['_SIMULATIONSERVICE']._serialized_start=450
  _globals['_SIMULATIONSERVICE']._serialized_end=542
# @@protoc_insertion_point(module_scope)
